# ~/.config/nearby/config.toml
# Optional: only lock/unlock sessions for a specific seat
# seat = "seat0"

[[connection]]
name = "My Watch"
type = "ble"
mac = "AA:BB:CC:DD:EE:FF"
owner = "self"
actions = [
	{ type = "away", threshold=2.0, command = "lock"},
	{ type = "nearby", threshold=1.0, command = "unlock"},
]

[[connection]]
name = "My Phone"
type = "ble"
mac = "AA:BB:CC:DD:EE:FF"
owner = "self"
actions = [
	{ type = "away", threshold=1.0, command = "lock"},
	{ type = "nearby", threshold=2.0, command = "keep-unlocked"},
]
